FROM resin/%%RESIN_MACHINE_NAME%%-openjdk:8-jdk

RUN install_packages maven

WORKDIR /usr/src/app

COPY . .

RUN mvn clean install

CMD java -jar target/kotlin-balena-1.0-SNAPSHOT-jar-with-dependencies.jar